### ISSUE TITLE
Compile NEMO on ADA

### ISSUE THREAD

**Issue by jenniferagraham** [CefasRepRes/NEMO4.0-FABM#1]
To compile on ADA, need to also link to XIOS and FABM, so ensure these are compiled first. 

Recommended modules to start with are: 
```
gcc/9.2.0 
netcdf/4.7.4/parallel/gcc-openmpi 
hdf5/1.10.6/gcc-openmpi
mpi/openmpi/4.0.3/gcc/ib 
perl/5.30.2
```

**Comment by tiagoams** [comment]
I managed to compile configuration AMM7-FABM using intel 2020-04 modules. 

3453d8ff3d749faea0caab77ac96aed8ca5b5296

Still haven't ran tests
